### ISSUE TITLE
tuple index out of range/KIER+altop/docred

### ISSUE THREAD

**Issue by wucui5** [nju-websoft/KIRE#5]
Hello, I encountered this issue when trying to replicate your framework on the ALTOP model with the DocRED dataset. Any help would be greatly appreciated.
Traceback (most recent call last):
File "train.py", line 435, in <module>
main()
File "train.py", line 425, in main
dev_score, dev_output = evaluate(args, model, dev_features, tag="dev")
File "train.py", line 214, in evaluate
dids = batch[5]
IndexError: tuple index out of range

**Comment by njuxinyiwang** [comment]
Hello,
1. Regarding the ALTOP model you mentioned, do you mean the ATLOP model? Actually, we have provided our framework on the ATLOP model in the directory "ATLOP+KIRE".
2. Regarding the IndexError, there may be something wrong with your dataloader. You can try to print the "batch" tuple to find the reason.

**Comment by n-m-h** [comment]
你好，我按照readme文件的步骤下载数据集，模型，然后运行脚本。
但是没有成功，这是什么问题啊？我并没有漏掉要下载的文件啊。
<img width="290" alt="iShot_2024-04-22_21 02 10" src="https://github.com/nju-websoft/KIRE/assets/144300788/2350da80-cba6-469c-8885-351b9c77e221">
<img width="768" alt="iShot_2024-04-22_21 03 31" src="https://github.com/nju-websoft/KIRE/assets/144300788/d8354087-4d3f-49a1-a5e1-ccf5157979a3">

**Comment by n-m-h** [comment]
盼回复。。

**Comment by njuxinyiwang** [comment]
你好，需要你在ATLOP+KIRE文件夹下自行创建一个logs文件夹用于存储log文件。

**Comment by n-m-h** [comment]
不好意思啊，我刚学这个。如果要成功运行的话，我除了根据readme文件描述操作，还需要执行别的吗，比如执行train.py文件等。如果是要运行train.py的话，我报了个错误，维度匹配问题，排查了一天也没找到，您能指点一在吗？
<img width="1316" alt="iShot_2024-04-23_10 08 20" src="https://github.com/nju-websoft/KIRE/assets/144300788/a869f7a8-dac5-4ad4-ae57-5085de513eec">

**Comment by njuxinyiwang** [comment]
按照readme执行，执行的sh文件里规定了train.py运行时的参数。
